# Crawler 01: DCard
- 設計爬蟲去爬取DCard任一版的文章，可以爬取熱門文章或最新文章均可。
- 目標是爬取100則不重複的貼文
- 必須用for-loop迴圈爬取，不得分開爬取多個不同的網址。
- 重要提示: DCard的資料網址並沒有頁碼可以參考，但每一頁最後一筆資料的id，均為下一頁資料的網址的一部分。所以這題的for-loop並不是要算頁碼用的，單純只是讓程式多跑幾遍，每次都去取當頁資料的最後一筆id，來剪貼成下一頁資料的網址。
- 注意，dcard的request會需要附加user-agent資訊。

In [35]:
# sample code of getting dcard data with user-agent info
import requests

url_dcard = "https://www.dcard.tw/_api/forums/relationship/posts?popular=true"
user_agent_dcard = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
headers = {
    'User-Agent': user_agent_dcard
}
data = requests.get(url_dcard, headers = headers).json()
type(data)

list

In [45]:
# Your code should be here
# You can add more code cells below this
import requests
import json
url_dcard = "https://www.dcard.tw/service/api/v2/forums/ntu/posts?limit=30&before=237386783"
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
response = requests.get(url_dcard, timeout = (3, 5))

#print(response.status_code)
#print(response.headers)
#print(response.text)

headers = {
    'User-Agent' : user_agent
}
data_dcard = requests.get(url_dcard, headers = headers).json()
type(data_dcard)

#print(len(data_dcard))
#print(data_dcard[29])

#copy last id of each page to add to the next page's url
all_data = []
for page in range(1, 5):
  if (page == 1):
    last_id = 237386783
  url = 'https://www.dcard.tw/service/api/v2/forums/ntu/posts?limit=30&before='+ str(last_id)
  raw = requests.get(url, headers = headers).json()
  last_id = raw[len(raw)-1]['id']
  all_data.extend(raw)
  print(len(raw), last_id, url)

print(len(all_data))

30 237375201 https://www.dcard.tw/service/api/v2/forums/ntu/posts?limit=30&before=237386783
30 237366818 https://www.dcard.tw/service/api/v2/forums/ntu/posts?limit=30&before=237375201
30 237360186 https://www.dcard.tw/service/api/v2/forums/ntu/posts?limit=30&before=237366818
30 237350256 https://www.dcard.tw/service/api/v2/forums/ntu/posts?limit=30&before=237360186
120



```
https://www.dcard.tw/service/api/v2/forums/ntu/posts?limit=30&before=237386783

https://www.dcard.tw/service/api/v2/forums/ntu/posts?limit=30&before=237375201

https://www.dcard.tw/service/api/v2/forums/ntu/posts?limit=30&before=237366818
```

## Output verification
以下程式碼是為了檢測同學所交上了的作業是否確實抓到對的資料。通常會用以下幾種方式來確認。
1. 確認資料筆數
2. 找到資料中能夠作為identification的欄位，取`set()`來看看是否和抓到的資料筆數相同。

### 1. Convert your list of dicts into a pandas DataFrame
**MUST** using `df_dcard` as variable name of the pandas Dataframe

In [47]:
## your code should be here
import pandas as pd
df_dcard = pd.DataFrame(all_data)
## your code should be here
df_dcard = df_dcard.drop_duplicates('title')
df_dcard

            id                   title  ... verifiedBadge  memberType
0    237386698                 野生優質理工男  ...         False
1    237385854                     普化丙  ...         False
2    237385835             在臺大要怎麼認識外籍生  ...         False
3    237384904           有沒有台大第一系法律系的卦  ...         False
4    237384234        ［徵］ 葉德銘教授—觀葉植物考古  ...         False
..         ...                     ...  ...           ...         ...
115  237350914  台大男生會覺得民族國中的女生很可愛想認識嗎？  ...         False
116  237350833               前文組人的心酸告白  ...         False
117  237350813                  猜猜他是誰？  ...         False
118  237350304                POE更新不完啦  ...         False
119  237350256               學校好多地方都沒開  ...         False

[120 rows x 47 columns]

### 2. Print `df_dcard.shape`

In [48]:
df_dcard.shape

(120, 47)

### 3. Print the number of unique id
unique id的數量必須要100以上（包含100）

In [49]:
print(len(set(df_dcard.id)))

120

In [77]:
%whos

Variable           Type         Data/Info
-----------------------------------------
all_data           list         n=120
data               list         n=30
data_dcard         list         n=30
df_dcard           DataFrame                id           <...>\n[120 rows x 47 columns]
headers            dict         n=1
i                  dict         n=45
id                 int          2
json               module       <module 'json' from '/usr<...>hon3.7/json/__init__.py'>
last_id            int          237350256
page               int          4
pd                 module       <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
raw                list         n=30
requests           module       <module 'requests' from '<...>es/requests/__init__.py'>
response           Response     <Response [200]>
url                str          https://www.dcard.tw/serv<...>limit=30&before=237360186
url_dcard          str          https://www.dcard.tw/serv<...>limit=30&before=237386783
user_agent         str          Mozilla/5.0 (Macintosh; I<...>5.0.4638.69 Safari/537.36
user_agent_dcard   str          Mozilla/5.0 (Macintosh; I<...>5.0.4638.54 Safari/537.36

# Crawler 02: cnyer
- 設計爬蟲去爬取鉅亨網的新聞（https://news.cnyes.com/news/cat/headline?exp=a）。
- 目標是爬取100則不重複的新聞
- 必須用for-loop迴圈爬取，不得分開爬取多個不同的網址。

In [50]:
# YOUR CODE SHOULD BE HERE
import requests
import json
url_cnyes = "https://api.cnyes.com/media/api/v1/newslist/category/headline?limit=30&startAt=1635350400&endAt=1636300799&page=5"
headers_cnyes = {'refer':'https://news.cnyes.com/'}
response_cnyes = requests.get(url_cnyes, headers = headers_cnyes)

#print(response.status_code)
#print(response.headers)
#print(response.text)

data_cnyes = response_cnyes.json()
#type(data_cnyes)
#print(data_cnyes.keys())
#print(data_cnyes['items'])
#print(data_cnyes['items']['data'])
#print(len(data_cnyes['items']['data']))

all_data_cnyes = []
for page in range(5,9):
  url = "https://api.cnyes.com/media/api/v1/newslist/category/headline?limit=30&startAt=1635350400&endAt=1636300799&page="+str(page)
  raw_cnyes = requests.get(url, headers= headers_cnyes).json()
  print('Page:', page, 'Data length:' ,len(raw_cnyes['items']['data']))
  all_data_cnyes.extend(raw_cnyes['items']['data'])

Page: 5 Data length: 30
Page: 6 Data length: 30
Page: 7 Data length: 30
Page: 8 Data length: 30



```
https://api.cnyes.com/media/api/v1/newslist/category/headline?limit=30&startAt=1635350400&endAt=1636300799&page=5
https://api.cnyes.com/media/api/v1/newslist/category/headline?limit=30&startAt=1635350400&endAt=1636300799&page=6
https://api.cnyes.com/media/api/v1/newslist/category/headline?limit=30&startAt=1635350400&endAt=1636300799&page=7
```

## Output Verification

### 1. Convert your list of dicts into a pandas DataFrame
**MUST** using `df_cnyes` as variable name of the pandas Dataframe

In [53]:
# code should be here
import pandas as pd
df_cnyes = pd.DataFrame(all_data_cnyes)
df_cnyes
# code should be here
df_cnyes = df_cnyes.drop_duplicates('newsId')
df_cnyes

      newsId  ...                                             market
0    4762322  ...                                                NaN
1    4762308  ...                                                NaN
2    4762288  ...  [{'code': '2498', 'name': '宏達電', 'symbol': 'TW...
3    4762307  ...  [{'code': '6415', 'name': '矽力-KY', 'symbol': '...
4    4762305  ...                                                NaN
..       ...  ...                                                ...
115  4761337  ...                                                NaN
116  4761352  ...                                                NaN
117  4761278  ...                                                NaN
118  4761317  ...                                                NaN
119  4761314  ...  [{'code': '1727', 'name': '中華化', 'symbol': 'TW...

[120 rows x 22 columns]

### 2. Print `df_cnyes.shape()`

In [54]:
df_cnyes.shape

(120, 22)

### 3. Print the number of unique id
unique newsId的數量必須要100以上（包含100）

In [55]:
print(len(set(df_cnyes.newsId)))

120